stages:
  - preflight
  - deploy

.preflight: &preflight
  image: node:18.16.0-alpine
  stage: preflight
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  before_script:
    - npm install --prefer-offline

build:
  <<: *preflight
  script:
    - npm run ci:build
  artifacts:
    paths:
      - ./build

format:
  <<: *preflight
  script:
    - npm run ci:format

lint:
  <<: *preflight
  script:
    - npm run ci:lint

test:
  <<: *preflight
  script:
    - npm run ci:test

typecheck:
  <<: *preflight
  script:
    - npm run ci:typecheck

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 rm s3://${AWS_BUCKET_NAME} --recursive
    - aws s3 cp ./build s3://${AWS_BUCKET_NAME} --recursive
    - aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID}  --paths "/*"
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
