stages:
  - build
  - deploy

build:
  image: node:20-alpine
  stage: build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  before_script:
    - npm install --prefer-offline
  script:
    - npm run build
  artifacts:
    paths:
      - ./public

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 rm s3://${AWS_BUCKET_NAME} --recursive
    - aws s3 cp ./public s3://${AWS_BUCKET_NAME} --recursive
    - aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID}  --paths "/*"
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
